//! CheapTrick accuracy validation against the C++ reference (Phase 2-7).
//!
//! Reference vectors are generated by the C++ harness
//! (`test-vector-data/cheaptrick_reference.cpp`) via
//! `bash test-vector-data/generate-cheaptrick-vectors.sh`. This test reads the
//! binary reference files and compares the Rust [`cheaptrick`] output against
//! them using the PSNR metric: `PSNR = 10 * log10(MAX^2 / MSE)` with `MAX`
//! pinned to `1e6` (a data-independent constant, per PHASE2-7) and `MSE` the
//! mean squared error across all frames and frequency bins. Acceptance:
//! PSNR > 40 dB on every test vector.
//!
//! The test set covers the cases required by PHASE2-7:
//! - a 440 Hz sine at 16 kHz and 48 kHz (different sampling rates),
//! - a fully unvoiced contour (F0 = 0 for all frames, exercising the
//!   `kDefaultF0 = 500` path),
//! - a voiced -> unvoiced transition contour,
//! - a linear chirp contour (voiced, varying F0).
//
// Test target: unwrap/panic in setup and assertions is expected.
#![allow(clippy::unwrap_used)]
#![allow(clippy::panic)]

use std::fs;
use std::path::PathBuf;

use world_rs::cheaptrick::{cheaptrick, initialize_cheaptrick_option};

mod common;
use common::{manifest_dir, psnr_2d};

/// The deterministic test signals + F0 contours (see `cheaptrick_reference.cpp`).
const TEST_NAMES: &[&str] = &[
    "sine_440_16k",
    "sine_440_48k",
    "unvoiced_16k",
    "transition_16k",
    "chirp_16k",
];

/// Root of the committed reference vectors (workspace `test-vector-data/`).
fn vectors_dir() -> PathBuf {
    manifest_dir().join("../../test-vector-data/vectors/cheaptrick")
}

/// A reference case: the input signal, the F0 contour / temporal positions, and
/// the C++ `CheapTrick()` spectrogram.
struct Reference {
    x: Vec<f64>,
    fs: f64,
    f0: Vec<f64>,
    temporal_positions: Vec<f64>,
    spectrogram: Vec<Vec<f64>>,
    fft_size: i32,
}

fn read_f64s(bytes: &[u8]) -> Vec<f64> {
    let (chunks, _rest) = bytes.as_chunks::<8>();
    chunks.iter().map(|c| f64::from_le_bytes(*c)).collect()
}

fn read_reference(name: &str) -> Reference {
    let dir = vectors_dir();
    let in_path = dir.join(format!("{name}.in"));
    let out_path = dir.join(format!("{name}.out"));
    let hint = "run `bash test-vector-data/generate-cheaptrick-vectors.sh` to generate them";
    assert!(in_path.exists(), "missing {in_path:?}; {hint}");
    assert!(out_path.exists(), "missing {out_path:?}; {hint}");

    // <name>.in : u32 x_length, f64 fs, x_length * f64 samples
    let in_bytes = fs::read(&in_path).unwrap();
    let x_length = u32::from_le_bytes(in_bytes[0..4].try_into().unwrap()) as usize;
    let fs = f64::from_le_bytes(in_bytes[4..12].try_into().unwrap());
    let x = read_f64s(&in_bytes[12..]);
    assert_eq!(x.len(), x_length, "{name}: input length mismatch");

    // <name>.out: u32 f0_length, u32 fft_size,
    //             f0_length * f64 f0, f0_length * f64 temporal_positions,
    //             f0_length * (fft_size/2 + 1) * f64 spectrogram
    let out_bytes = fs::read(&out_path).unwrap();
    let f0_length = u32::from_le_bytes(out_bytes[0..4].try_into().unwrap()) as usize;
    let fft_size = i32::from_le_bytes(out_bytes[4..8].try_into().unwrap());
    let half = (fft_size / 2) as usize + 1;

    let f0_span = 8..8 + f0_length * 8;
    let tp_span = f0_span.end..f0_span.end + f0_length * 8;
    let f0 = read_f64s(&out_bytes[f0_span.clone()]);
    let temporal_positions = read_f64s(&out_bytes[tp_span.clone()]);
    let sp_bytes = &out_bytes[tp_span.end..];
    let spectrogram: Vec<Vec<f64>> = sp_bytes.chunks_exact(half * 8).map(read_f64s).collect();

    assert_eq!(f0.len(), f0_length, "{name}: f0 length mismatch");
    assert_eq!(
        temporal_positions.len(),
        f0_length,
        "{name}: temporal length mismatch"
    );
    assert_eq!(
        spectrogram.len(),
        f0_length,
        "{name}: spectrogram frame count mismatch"
    );
    for (i, row) in spectrogram.iter().enumerate() {
        assert_eq!(
            row.len(),
            half,
            "{name}: spectrogram row {i} length mismatch"
        );
    }

    Reference {
        x,
        fs,
        f0,
        temporal_positions,
        spectrogram,
        fft_size,
    }
}

/// Pearson correlation between the flattened Rust and reference spectrograms.
fn correlation(rust: &[Vec<f64>], reference: &[Vec<f64>]) -> f64 {
    assert_eq!(rust.len(), reference.len(), "frame count mismatch");
    let mut a: Vec<f64> = Vec::with_capacity(rust.len() * rust[0].len());
    let mut b: Vec<f64> = Vec::with_capacity(reference.len() * reference[0].len());
    for (r, ref_row) in rust.iter().zip(reference) {
        a.extend_from_slice(r);
        b.extend_from_slice(ref_row);
    }
    let n = a.len() as f64;
    let mean_a: f64 = a.iter().sum::<f64>() / n;
    let mean_b: f64 = b.iter().sum::<f64>() / n;
    let (mut cov, mut va, mut vb) = (0.0f64, 0.0f64, 0.0f64);
    for (x, y) in a.iter().zip(b) {
        let da = x - mean_a;
        let db = y - mean_b;
        cov += da * db;
        va += da * da;
        vb += db * db;
    }
    cov / (va.sqrt() * vb.sqrt())
}

/// Runs the Rust `cheaptrick()` on a reference case and returns the Rust
/// spectrogram. Also asserts the structural contract (output shape, temporal
/// grid) against the reference.
fn run_case(name: &str) -> (Vec<Vec<f64>>, Reference) {
    let reference = read_reference(name);
    let option = initialize_cheaptrick_option(reference.fs);
    assert_eq!(
        option.fft_size, reference.fft_size,
        "{name}: fft_size mismatch (rust {} vs ref {})",
        option.fft_size, reference.fft_size
    );
    let result = cheaptrick(
        &reference.x,
        reference.fs,
        &reference.temporal_positions,
        &reference.f0,
        &option,
    )
    .expect("valid input");

    assert_eq!(
        result.len(),
        reference.f0.len(),
        "{name}: frame count mismatch"
    );
    for (i, row) in result.iter().enumerate() {
        assert_eq!(
            row.len(),
            (reference.fft_size / 2) as usize + 1,
            "{name}: row {i} bin count mismatch"
        );
    }

    (result, reference)
}

/// Acceptance: PSNR > 40 dB vs the C++ reference on every test vector.
#[test]
fn cheaptrick_psnr_above_40db_on_all_vectors() {
    for name in TEST_NAMES {
        let (result, reference) = run_case(name);
        let value = psnr_2d(&result, &reference.spectrogram);
        assert!(value > 40.0, "{name}: PSNR {value} dB is not > 40 dB");
    }
}

/// Acceptance: the spectral envelope (SP) correlates > 0.99 with the C++
/// reference on every test vector (SP correlation criterion from the test
/// vector README / global spec).
#[test]
fn cheaptrick_sp_correlation_above_099_on_all_vectors() {
    for name in TEST_NAMES {
        let (result, reference) = run_case(name);
        let corr = correlation(&result, &reference.spectrogram);
        assert!(corr > 0.99, "{name}: SP correlation {corr} is not > 0.99");
    }
}

/// Structural: every envelope value is finite and strictly positive (the
/// `add_infinitesimal_noise` + `exp` pipeline guarantees a positive envelope).
#[test]
fn cheaptrick_output_finite_and_positive_on_all_vectors() {
    for name in TEST_NAMES {
        let (result, _) = run_case(name);
        for (i, row) in result.iter().enumerate() {
            for (j, &v) in row.iter().enumerate() {
                assert!(
                    v.is_finite() && v > 0.0,
                    "{name}: frame {i} bin {j} not finite/positive: {v}"
                );
            }
        }
    }
}

/// Acceptance: unvoiced frames produce a stable spectral envelope. A fully
/// unvoiced contour (F0 = 0 for all frames) drives every frame through the
/// `kDefaultF0 = 500` path; the resulting envelope must be finite, positive,
/// and match the C++ reference (PSNR > 40 dB).
#[test]
fn cheaptrick_unvoiced_frames_stable() {
    let (result, reference) = run_case("unvoiced_16k");
    // All reference frames are unvoiced.
    assert!(
        reference.f0.iter().all(|&v| v == 0.0),
        "unvoiced_16k reference is not fully unvoiced"
    );
    for row in &result {
        for &v in row {
            assert!(
                v.is_finite() && v > 0.0,
                "unvoiced envelope not finite/positive: {v}"
            );
        }
    }
    let value = psnr_2d(&result, &reference.spectrogram);
    assert!(value > 40.0, "unvoiced_16k: PSNR {value} dB is not > 40 dB");
}

/// The voiced -> unvoiced transition contour must be handled without error and
/// match the C++ reference; the envelope stays finite/positive across the
/// boundary.
#[test]
fn cheaptrick_transition_contour_matches_reference() {
    let (result, reference) = run_case("transition_16k");
    let half = reference.f0.len() / 2;
    // The contour actually transitions: first half voiced, second half unvoiced.
    assert!(
        reference.f0[half - 1] > 0.0,
        "transition: first half not voiced"
    );
    assert!(
        reference.f0[half] == 0.0,
        "transition: second half not unvoiced"
    );
    let value = psnr_2d(&result, &reference.spectrogram);
    assert!(
        value > 40.0,
        "transition_16k: PSNR {value} dB is not > 40 dB"
    );
    for row in &result {
        for &v in row {
            assert!(
                v.is_finite() && v > 0.0,
                "transition envelope not finite/positive: {v}"
            );
        }
    }
}

/// Different sampling rates (16 kHz and 48 kHz) both match the C++ reference.
/// The 48 kHz case exercises a larger `fft_size` (2048 vs 1024).
#[test]
fn cheaptrick_sampling_rates_16k_and_48k() {
    for name in ["sine_440_16k", "sine_440_48k"] {
        let (result, reference) = run_case(name);
        let value = psnr_2d(&result, &reference.spectrogram);
        assert!(value > 40.0, "{name}: PSNR {value} dB is not > 40 dB");
    }
    // Confirm the two rates really do use different FFT sizes.
    let fs16 = read_reference("sine_440_16k").fft_size;
    let fs48 = read_reference("sine_440_48k").fft_size;
    assert_ne!(fs16, fs48, "expected distinct fft_size for 16k vs 48k");
}
