//! MATLAB functions accuracy validation against C++ reference.
//!
//! Reference vectors generated by test-vector-data/interp1q_reference.cpp via
//! `bash test-vector-data/generate-interp1q-vectors.sh`.

#![allow(clippy::unwrap_used)]
#![allow(clippy::panic)]

use std::fs;
use std::path::PathBuf;

use world_rs_core::matlab::interp1q;

fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../test-vector-data/vectors/matlab")
}

fn read_f64s(bytes: &[u8]) -> Vec<f64> {
    bytes
        .as_chunks::<8>()
        .0
        .iter()
        .map(|c| f64::from_le_bytes(*c))
        .collect()
}

struct Interp1qCase {
    x0: f64,
    shift: f64,
    y: Vec<f64>,
    xi: Vec<f64>,
    yi_ref: Vec<f64>,
}

fn read_interp1q(name: &str) -> Interp1qCase {
    let dir = vectors_dir();
    let in_path = dir.join(format!("{name}.in"));
    let out_path = dir.join(format!("{name}.out"));
    let hint = "run `bash test-vector-data/generate-interp1q-vectors.sh` to generate them";
    assert!(in_path.exists(), "missing {in_path:?}; {hint}");
    assert!(out_path.exists(), "missing {out_path:?}; {hint}");

    let in_bytes = fs::read(&in_path).unwrap();
    let y_len = u32::from_le_bytes(in_bytes[0..4].try_into().unwrap()) as usize;
    let x0 = f64::from_le_bytes(in_bytes[4..12].try_into().unwrap());
    let shift = f64::from_le_bytes(in_bytes[12..20].try_into().unwrap());
    let y_start = 20;
    let y_end = y_start + y_len * 8;
    let y = read_f64s(&in_bytes[y_start..y_end]);
    let xi_len = u32::from_le_bytes(in_bytes[y_end..y_end + 4].try_into().unwrap()) as usize;
    let xi_start = y_end + 4;
    let xi = read_f64s(&in_bytes[xi_start..xi_start + xi_len * 8]);
    assert_eq!(y.len(), y_len);
    assert_eq!(xi.len(), xi_len);

    let out_bytes = fs::read(&out_path).unwrap();
    let yi_len = u32::from_le_bytes(out_bytes[0..4].try_into().unwrap()) as usize;
    let yi_ref = read_f64s(&out_bytes[4..]);
    assert_eq!(yi_ref.len(), yi_len);
    assert_eq!(yi_len, xi_len);

    Interp1qCase {
        x0,
        shift,
        y,
        xi,
        yi_ref,
    }
}

#[test]
fn interp1q_grid_aligned_parity() {
    let case = read_interp1q("interp1q_grid");
    let mut yi = vec![0.0; case.xi.len()];
    interp1q(case.x0, case.shift, &case.y, &case.xi, &mut yi);
    for (i, (a, b)) in yi.iter().zip(case.yi_ref.iter()).enumerate() {
        let diff = (a - b).abs();
        assert!(
            diff <= 1e-12,
            "interp1q_grid[{i}] rust={a} cpp={b} diff={diff}"
        );
    }
}

#[test]
fn interp1q_negative_shift_parity() {
    let case = read_interp1q("interp1q_negative");
    let mut yi = vec![0.0; case.xi.len()];
    interp1q(case.x0, case.shift, &case.y, &case.xi, &mut yi);
    for (i, (a, b)) in yi.iter().zip(case.yi_ref.iter()).enumerate() {
        let diff = (a - b).abs();
        assert!(
            diff <= 1e-12,
            "interp1q_negative[{i}] rust={a} cpp={b} diff={diff}"
        );
    }
}

#[test]
fn interp1q_boundary_parity() {
    let case = read_interp1q("interp1q_boundary");
    let mut yi = vec![0.0; case.xi.len()];
    interp1q(case.x0, case.shift, &case.y, &case.xi, &mut yi);
    for (i, (a, b)) in yi.iter().zip(case.yi_ref.iter()).enumerate() {
        let diff = (a - b).abs();
        // Rust clamps OOB to y[0]; C++ reads out-of-bounds (UB). For in-range points we expect exact parity.
        // For OOB we allow divergence but document it.
        if case.xi[i] < case.x0 || case.xi[i] > case.x0 + case.shift * (case.y.len() as f64 - 1.0) {
            // OOB region: Rust returns y[0], C++ is UB. We only assert for in-range.
            continue;
        }
        assert!(
            diff <= 1e-12,
            "interp1q_boundary[{i}] rust={a} cpp={b} diff={diff}"
        );
    }
}
