//! Resample accuracy validation against the JS polyphase reference (Phase 4-8).
//!
//! Reference vectors are generated by the JS driver
//! (`test-vector-data/resample_reference.mjs`) via
//! `bash test-vector-data/generate-resample-vectors.sh`. This test reads the
//! binary reference files and compares the Rust [`resample`] output against
//! them using the PSNR metric: `PSNR = 10 * log10(MAX^2 / MSE)` with `MAX`
//! pinned to `1e6` (a data-independent constant, per PHASE2-7) and `MSE` the
//! mean squared error across all output samples. Acceptance: PSNR > 40 dB on
//! every test vector. Because the Rust port is a bit-for-bit port of the JS
//! `@audio/resample-polyphase` atom, the outputs are additionally checked to
//! match exactly (max absolute error == 0).
//!
//! The test set covers the cases required by PHASE4-8:
//! - a 440 Hz sine at 16k -> 48k (3:1 upsample) and 48k -> 16k (1:3 downsample),
//! - a 440 Hz sine at 44100 -> 48000 (non-integer rational ratio, L/M = 160/147),
//! - a max-amplitude full-scale Nyquist square at 16k -> 48k,
//! - a 100 -> 15000 Hz swept sine at 48k -> 16k (anti-aliasing).

// Test target: unwrap/panic in setup and assertions is expected.
#![allow(clippy::unwrap_used)]
#![allow(clippy::panic)]

use std::fs;
use std::path::PathBuf;

use world_rs::resample::resample;

mod common;
use common::{manifest_dir, psnr_f32};

/// The deterministic resample cases (see `resample_reference.mjs`).
const TEST_NAMES: &[&str] = &[
    "sine440_16k_to_48k",
    "sine440_48k_to_16k",
    "sine440_44100_to_48000",
    "maxamp_16k_to_48k",
    "swept_48k_to_16k",
];

/// Root of the committed reference vectors (workspace `test-vector-data/`).
fn vectors_dir() -> PathBuf {
    manifest_dir().join("../../test-vector-data/vectors/resample")
}

fn read_f32s(bytes: &[u8]) -> Vec<f32> {
    bytes
        .as_chunks::<4>()
        .0
        .iter()
        .map(|c| f32::from_le_bytes(*c))
        .collect()
}

/// A reference case: the f32 input PCM and the JS polyphase reference output.
struct Reference {
    from: u32,
    to: u32,
    x: Vec<f32>,
    y: Vec<f32>,
}

fn read_reference(name: &str) -> Reference {
    let dir = vectors_dir();
    let in_path = dir.join(format!("{name}.in"));
    let out_path = dir.join(format!("{name}.out"));
    let hint = "run `bash test-vector-data/generate-resample-vectors.sh` to generate them";
    assert!(in_path.exists(), "missing {in_path:?}; {hint}");
    assert!(out_path.exists(), "missing {out_path:?}; {hint}");

    // <name>.in : u32 n, n * f32 input samples
    let in_bytes = fs::read(&in_path).unwrap();
    let n = u32::from_le_bytes(in_bytes[0..4].try_into().unwrap()) as usize;
    let x = read_f32s(&in_bytes[4..]);
    assert_eq!(x.len(), n, "{name}: input length mismatch");

    // <name>.out: u32 from, u32 to, u32 m, m * f32 reference output samples
    let out_bytes = fs::read(&out_path).unwrap();
    let from = u32::from_le_bytes(out_bytes[0..4].try_into().unwrap());
    let to = u32::from_le_bytes(out_bytes[4..8].try_into().unwrap());
    let m = u32::from_le_bytes(out_bytes[8..12].try_into().unwrap()) as usize;
    let y = read_f32s(&out_bytes[12..]);
    assert_eq!(y.len(), m, "{name}: output length mismatch");

    Reference { from, to, x, y }
}

/// Max absolute error (f32) between the Rust output and the reference.
fn max_abs_err(rust: &[f32], reference: &[f32]) -> f64 {
    assert_eq!(rust.len(), reference.len(), "length mismatch");
    rust.iter()
        .zip(reference)
        .map(|(a, b)| (*a - *b).abs() as f64)
        .fold(0.0f64, f64::max)
}

/// Runs the Rust `resample` on a reference case and returns the Rust output.
/// Also asserts the structural contract (output length equals the reference).
fn run_case(name: &str) -> (Vec<f32>, Reference) {
    let reference = read_reference(name);
    let y = resample(&reference.x, reference.from, reference.to);
    assert_eq!(y.len(), reference.y.len(), "{name}: output length mismatch");
    (y, reference)
}

/// PSNR > 40 dB against the JS polyphase reference on every test vector
/// (PHASE4-8 acceptance criteria).
#[test]
fn resample_matches_js_reference_psnr() {
    for name in TEST_NAMES {
        let (y, reference) = run_case(name);
        let p = psnr_f32(&y, &reference.y);
        assert!(
            p > 40.0,
            "{name}: PSNR {} dB not > 40 dB",
            if p.is_infinite() {
                "inf".to_string()
            } else {
                format!("{p:.2}")
            }
        );
    }
}

/// The Rust port is bit-for-bit identical to the JS polyphase reference: the
/// max absolute error over every output sample is exactly 0 on every test
/// vector (PHASE4-8: "match the JS polyphase reference bit-for-bit").
#[test]
fn resample_matches_js_reference_bit_for_bit() {
    for name in TEST_NAMES {
        let (y, reference) = run_case(name);
        let err = max_abs_err(&y, &reference.y);
        assert_eq!(err, 0.0, "{name}: max abs error {err} (want 0)");
    }
}

/// PSNR for the 16k -> 48k (3:1 upsample) conversion exceeds 40 dB
/// (PHASE4-8: "Measure PSNR for 16k->48k and 48k->16k conversions").
#[test]
fn resample_psnr_16k_to_48k() {
    let (y, reference) = run_case("sine440_16k_to_48k");
    assert_eq!(reference.from, 16000);
    assert_eq!(reference.to, 48000);
    let p = psnr_f32(&y, &reference.y);
    assert!(
        p > 40.0,
        "16k->48k PSNR {} dB not > 40 dB",
        if p.is_infinite() {
            "inf".to_string()
        } else {
            format!("{p:.2}")
        }
    );
}

/// PSNR for the 48k -> 16k (1:3 downsample) conversion exceeds 40 dB
/// (PHASE4-8: "Measure PSNR for 16k->48k and 48k->16k conversions").
#[test]
fn resample_psnr_48k_to_16k() {
    let (y, reference) = run_case("sine440_48k_to_16k");
    assert_eq!(reference.from, 48000);
    assert_eq!(reference.to, 16000);
    let p = psnr_f32(&y, &reference.y);
    assert!(
        p > 40.0,
        "48k->16k PSNR {} dB not > 40 dB",
        if p.is_infinite() {
            "inf".to_string()
        } else {
            format!("{p:.2}")
        }
    );
}

/// Non-integer rational ratio: 44100 -> 48000 (reduced by gcd to L/M = 160/147)
/// confirms arbitrary-ratio support (PHASE4-8). The output length is
/// `round(n * to / from)`, the result is bit-for-bit identical to the JS
/// reference, and a 440 Hz tone is preserved at unity passband gain.
#[test]
fn resample_44100_to_48000_noninteger_ratio() {
    let (y, reference) = run_case("sine440_44100_to_48000");
    assert_eq!(reference.from, 44100);
    assert_eq!(reference.to, 48000);

    // Output length is round(n * to / from).
    let expected = (reference.x.len() as f64 * 48000.0 / 44100.0).round() as usize;
    assert_eq!(y.len(), expected, "44100->48000 output length");

    // Bit-for-bit against the JS reference (arbitrary-ratio support).
    assert_eq!(
        max_abs_err(&y, &reference.y),
        0.0,
        "44100->48000 not bit-for-bit"
    );

    // Unity passband gain: a unit 440 Hz sine has RMS sqrt(1/2) in the middle.
    let n = y.len();
    let a = n >> 3;
    let b = n - (n >> 3);
    let s: f64 = y[a..b].iter().map(|&v| v as f64 * v as f64).sum();
    let r = (s / (b - a) as f64).sqrt();
    assert!(
        (r - std::f64::consts::FRAC_1_SQRT_2).abs() < 1e-3,
        "44100->48000 440 Hz RMS {} not ≈ sqrt(1/2)",
        r
    );
}

/// Max-amplitude edge case: a full-scale (|x| <= 1) Nyquist square at 16k ->
/// 48k resamples to a finite, bounded output (PHASE4-8: "max amplitude"). The
/// polyphase taps sum to ~unity DC gain, so a full-scale input cannot drive the
/// output beyond a small margin above full scale; the result is bit-for-bit
/// identical to the JS reference.
#[test]
fn resample_max_amplitude_finite_bounded() {
    let (y, reference) = run_case("maxamp_16k_to_48k");
    assert_eq!(reference.from, 16000);
    assert_eq!(reference.to, 48000);

    // Every output sample is finite (no NaN/Inf) and bounded.
    let peak = y.iter().map(|&v| v.abs()).fold(0.0f32, f32::max);
    assert!(
        peak.is_finite(),
        "max-amplitude output peak {} not finite",
        peak
    );
    assert!(
        peak <= 1.5,
        "max-amplitude output peak {} exceeds full-scale margin",
        peak
    );

    // Bit-for-bit against the JS reference.
    assert_eq!(
        max_abs_err(&y, &reference.y),
        0.0,
        "max-amplitude not bit-for-bit"
    );
}

/// No aliasing artifacts on a swept sine (PHASE4-8): a 100 -> 15000 Hz chirp
/// at 48k downsampled to 16k. Content above the 8 kHz output Nyquist is
/// suppressed by the Kaiser anti-aliasing lowpass; the result is bit-for-bit
/// identical to the JS reference, so the aliasing matches the reference
/// exactly (PHASE4-8: "Aliasing of content above output Nyquist suppressed to
/// match the JS reference").
#[test]
fn resample_swept_sine_no_aliasing() {
    let (y, reference) = run_case("swept_48k_to_16k");
    assert_eq!(reference.from, 48000);
    assert_eq!(reference.to, 16000);

    // Bit-for-bit against the JS reference: the anti-aliasing (and hence the
    // aliasing) matches the reference exactly.
    assert_eq!(
        max_abs_err(&y, &reference.y),
        0.0,
        "swept sine 48k->16k not bit-for-bit"
    );

    // The output is finite and, because much of the chirp lies above the 8 kHz
    // output Nyquist and is suppressed, its middle-section RMS stays well below
    // the input's full-scale RMS (sqrt(1/2)).
    let n = y.len();
    let a = n >> 3;
    let b = n - (n >> 3);
    let s: f64 = y[a..b].iter().map(|&v| v as f64 * v as f64).sum();
    let r = (s / (b - a) as f64).sqrt();
    assert!(r.is_finite(), "swept sine output RMS {} not finite", r);
    assert!(
        r < std::f64::consts::FRAC_1_SQRT_2,
        "swept sine output RMS {} not below full-scale sqrt(1/2)",
        r
    );
}
