//! Synthesis accuracy validation against the C++ reference (Phase 3-9).
//!
//! Reference vectors are generated by the C++ harness
//! (`test-vector-data/synthesis_reference.cpp`) via
//! `bash test-vector-data/generate-synthesis-vectors.sh`. This test reads the
//! binary reference files and compares the Rust [`synthesis`] output against
//! them using the PSNR metric: `PSNR = 10 * log10(MAX^2 / MSE)` with `MAX`
//! pinned to `1e6` (a data-independent constant, per PHASE2-7) and `MSE` the
//! mean squared error across all output samples. Acceptance: PSNR > 40 dB on
//! every test vector, and a key-sample relative error < 1e-6.
//!
//! The test set covers the cases required by PHASE3-9:
//! - a constant 220 Hz voiced contour at 16 kHz and a 440 Hz contour at
//!   48 kHz (different sampling rates and FFT sizes),
//! - a linear chirp contour (100 -> 600 Hz, varying F0),
//! - a hard F0 discontinuity (200 Hz -> 500 Hz jump),
//! - a voiced -> unvoiced transition contour,
//! - a fully unvoiced contour (F0 = 0 for all frames, exercising the
//!   `kDefaultF0 = 500` path),
//! - a near-silence contour (F0 = 0, 1e-6-scaled envelope).

// Test target: unwrap/panic in setup and assertions is expected.
#![allow(clippy::unwrap_used)]
#![allow(clippy::panic)]

use std::fs;
use std::path::PathBuf;

use world_rs::synthesis::{get_y_length, synthesis};

mod common;
use common::{manifest_dir, psnr};

/// The deterministic test contours (see `synthesis_reference.cpp`).
const TEST_NAMES: &[&str] = &[
    "sine_220_16k",
    "chirp_16k",
    "jump_16k",
    "transition_16k",
    "unvoiced_16k",
    "silence_16k",
    "sine_440_48k",
];

/// Key samples (reference magnitude at or above this threshold) must match
/// the C++ reference within [`KEY_SAMPLE_REL_TOL`] relative error.
const KEY_SAMPLE_THRESHOLD: f64 = 1e-2;

/// Acceptance: key samples match within 1e-6 relative error (PHASE3-9).
const KEY_SAMPLE_REL_TOL: f64 = 1e-6;

/// Root of the committed reference vectors (workspace `test-vector-data/`).
fn vectors_dir() -> PathBuf {
    manifest_dir().join("../../test-vector-data/vectors/synthesis")
}

/// A reference case: the synthesis inputs (F0 contour, spectral envelope,
/// aperiodicity, parameters) and the C++ `Synthesis()` waveform.
struct Reference {
    f0: Vec<f64>,
    fs: f64,
    frame_period_ms: f64,
    fft_size: usize,
    spectrogram: Vec<Vec<f64>>,
    aperiodicity: Vec<Vec<f64>>,
    y: Vec<f64>,
}

fn read_f64s(bytes: &[u8]) -> Vec<f64> {
    let (chunks, _rest) = bytes.as_chunks::<8>();
    chunks.iter().map(|c| f64::from_le_bytes(*c)).collect()
}

fn read_reference(name: &str) -> Reference {
    let dir = vectors_dir();
    let in_path = dir.join(format!("{name}.in"));
    let out_path = dir.join(format!("{name}.out"));
    let hint = "run `bash test-vector-data/generate-synthesis-vectors.sh` to generate them";
    assert!(in_path.exists(), "missing {in_path:?}; {hint}");
    assert!(out_path.exists(), "missing {out_path:?}; {hint}");

    // <name>.in : u32 f0_length, u32 fft_size, f64 frame_period_ms, f64 fs,
    //             f0_length * f64 f0,
    //             f0_length * (fft_size/2 + 1) * f64 spectrogram,
    //             f0_length * (fft_size/2 + 1) * f64 aperiodicity
    let in_bytes = fs::read(&in_path).unwrap();
    let f0_length = u32::from_le_bytes(in_bytes[0..4].try_into().unwrap()) as usize;
    let fft_size = u32::from_le_bytes(in_bytes[4..8].try_into().unwrap()) as usize;
    let frame_period_ms = f64::from_le_bytes(in_bytes[8..16].try_into().unwrap());
    let fs = f64::from_le_bytes(in_bytes[16..24].try_into().unwrap());
    let half = fft_size / 2 + 1;

    let f0_span = 24..24 + f0_length * 8;
    let sp_span = f0_span.end..f0_span.end + f0_length * half * 8;
    let ap_span = sp_span.end..sp_span.end + f0_length * half * 8;
    let f0 = read_f64s(&in_bytes[f0_span.clone()]);
    let spectrogram: Vec<Vec<f64>> = read_f64s(&in_bytes[sp_span.clone()])
        .chunks(half)
        .map(|c| c.to_vec())
        .collect();
    let aperiodicity: Vec<Vec<f64>> = read_f64s(&in_bytes[ap_span.clone()])
        .chunks(half)
        .map(|c| c.to_vec())
        .collect();
    assert_eq!(f0.len(), f0_length, "{name}: f0 length mismatch");
    assert_eq!(
        spectrogram.len(),
        f0_length,
        "{name}: spectrogram frame count mismatch"
    );
    assert_eq!(
        aperiodicity.len(),
        f0_length,
        "{name}: aperiodicity frame count mismatch"
    );
    for (i, row) in spectrogram.iter().chain(aperiodicity.iter()).enumerate() {
        assert_eq!(row.len(), half, "{name}: row {i} bin count mismatch");
    }

    // <name>.out: u32 y_length, y_length * f64 y
    let out_bytes = fs::read(&out_path).unwrap();
    let y_length = u32::from_le_bytes(out_bytes[0..4].try_into().unwrap()) as usize;
    let y = read_f64s(&out_bytes[4..]);
    assert_eq!(y.len(), y_length, "{name}: y length mismatch");

    Reference {
        f0,
        fs,
        frame_period_ms,
        fft_size,
        spectrogram,
        aperiodicity,
        y,
    }
}

/// Max relative error over key samples (|reference| >= `threshold`), and the
/// number of key samples. Returns `(f64::NAN, 0)` when there are no key
/// samples.
fn key_sample_rel_err(rust: &[f64], reference: &[f64], threshold: f64) -> (f64, usize) {
    let mut max_rel = 0.0f64;
    let mut n = 0usize;
    for (a, b) in rust.iter().zip(reference) {
        if b.abs() >= threshold {
            max_rel = max_rel.max((a - b).abs() / b.abs());
            n += 1;
        }
    }
    if n == 0 {
        (f64::NAN, 0)
    } else {
        (max_rel, n)
    }
}

/// Runs the Rust `synthesis()` on a reference case and returns the Rust
/// waveform. Also asserts the structural contract (output length equals the
/// C++ `y_length` and `get_y_length`).
fn run_case(name: &str) -> (Vec<f64>, Reference) {
    let reference = read_reference(name);
    let y_length = get_y_length(reference.f0.len(), reference.frame_period_ms, reference.fs);
    assert_eq!(y_length, reference.y.len(), "{name}: y_length mismatch");
    let result = synthesis(
        &reference.f0,
        reference.f0.len(),
        &reference.spectrogram,
        &reference.aperiodicity,
        reference.fft_size,
        reference.frame_period_ms,
        reference.fs,
        y_length,
    )
    .expect("valid input");
    assert_eq!(
        result.len(),
        reference.y.len(),
        "{name}: output length mismatch"
    );
    (result, reference)
}

/// Acceptance: PSNR > 40 dB vs the C++ reference on every test vector.
#[test]
fn synthesis_psnr_above_40db_on_all_vectors() {
    for name in TEST_NAMES {
        let (result, reference) = run_case(name);
        let value = psnr(&result, &reference.y);
        assert!(value > 40.0, "{name}: PSNR {value} dB is not > 40 dB");
    }
}

/// Acceptance: key samples (|reference| >= 1e-2) match the C++ reference
/// within 1e-6 relative error on every test vector.
#[test]
fn synthesis_key_samples_within_1e6_relative_on_all_vectors() {
    for name in TEST_NAMES {
        let (result, reference) = run_case(name);
        let (max_rel, n) = key_sample_rel_err(&result, &reference.y, KEY_SAMPLE_THRESHOLD);
        assert!(
            n > 0,
            "{name}: no key samples (|ref| >= {KEY_SAMPLE_THRESHOLD})"
        );
        assert!(
            max_rel < KEY_SAMPLE_REL_TOL,
            "{name}: key-sample relative error {max_rel} (over {n} samples) is not < {KEY_SAMPLE_REL_TOL}"
        );
    }
}

/// Every output sample is finite on every test vector.
#[test]
fn synthesis_output_finite_on_all_vectors() {
    for name in TEST_NAMES {
        let (result, _) = run_case(name);
        for (i, &v) in result.iter().enumerate() {
            assert!(v.is_finite(), "{name}: sample {i} not finite: {v}");
        }
    }
}

/// Edge case (PHASE3-9): a hard F0 discontinuity (200 Hz -> 500 Hz at the
/// midpoint) and a varying-F0 chirp (100 -> 600 Hz) both match the C++
/// reference (PSNR > 40 dB) and stay finite.
#[test]
fn synthesis_f0_discontinuities_match_reference() {
    for name in ["jump_16k", "chirp_16k"] {
        let (result, reference) = run_case(name);
        // The contour really does jump / sweep.
        let mid = reference.f0.len() / 2;
        assert!(
            (reference.f0[mid - 1] - reference.f0[mid]).abs() >= 100.0
                || (reference.f0[mid] - reference.f0[0]).abs() >= 100.0,
            "{name}: contour does not vary"
        );
        let value = psnr(&result, &reference.y);
        assert!(value > 40.0, "{name}: PSNR {value} dB is not > 40 dB");
        for &v in &result {
            assert!(v.is_finite(), "{name}: non-finite sample");
        }
    }
}

/// Edge case (PHASE3-9): unvoiced segments. The voiced -> unvoiced transition
/// and the fully unvoiced contour (all frames through the `kDefaultF0 = 500`
/// path) match the C++ reference (PSNR > 40 dB) and stay finite.
#[test]
fn synthesis_unvoiced_segments_match_reference() {
    let (transition, ref_transition) = run_case("transition_16k");
    let half = ref_transition.f0.len() / 2;
    assert!(
        ref_transition.f0[half - 1] > 0.0,
        "transition: first half not voiced"
    );
    assert!(
        ref_transition.f0[half] == 0.0,
        "transition: second half not unvoiced"
    );
    let value = psnr(&transition, &ref_transition.y);
    assert!(
        value > 40.0,
        "transition_16k: PSNR {value} dB is not > 40 dB"
    );

    let (unvoiced, ref_unvoiced) = run_case("unvoiced_16k");
    assert!(
        ref_unvoiced.f0.iter().all(|&v| v == 0.0),
        "unvoiced_16k reference is not fully unvoiced"
    );
    let value = psnr(&unvoiced, &ref_unvoiced.y);
    assert!(value > 40.0, "unvoiced_16k: PSNR {value} dB is not > 40 dB");
    for &v in transition.iter().chain(unvoiced.iter()) {
        assert!(v.is_finite(), "unvoiced: non-finite sample");
    }
}

/// Edge case (PHASE3-9): near-silence. With a 1e-6-scaled envelope and an
/// all-unvoiced contour the output is finite and small: the envelope constant
/// is a log-domain offset, so the aperiodic noise response is scaled by
/// `1e-6` in magnitude (the periodic response is zero for unvoiced frames),
/// leaving an output ~1e-3x the normal-envelope magnitude. The result matches
/// the C++ reference (PSNR > 40 dB).
#[test]
fn synthesis_silence_stable() {
    let (result, reference) = run_case("silence_16k");
    assert!(
        reference.f0.iter().all(|&v| v == 0.0),
        "silence_16k reference is not fully unvoiced"
    );
    let max: f64 = result.iter().map(|v| v.abs()).fold(0.0, f64::max);
    assert!(max.is_finite(), "silence: non-finite output");
    assert!(max < 0.05, "silence: output magnitude {max} is not small");
    let value = psnr(&result, &reference.y);
    assert!(value > 40.0, "silence_16k: PSNR {value} dB is not > 40 dB");
}

/// The 16 kHz and 48 kHz vectors really do use different FFT sizes, and both
/// match the C++ reference (different `fs` / `fft_size` parameter paths).
#[test]
fn synthesis_sampling_rates_16k_and_48k() {
    let ref16 = read_reference("sine_220_16k");
    let ref48 = read_reference("sine_440_48k");
    assert_ne!(
        ref16.fft_size, ref48.fft_size,
        "expected distinct fft_size for 16k vs 48k"
    );
    assert_ne!(ref16.fs, ref48.fs, "expected distinct fs for 16k vs 48k");
    for name in ["sine_220_16k", "sine_440_48k"] {
        let (result, reference) = run_case(name);
        let value = psnr(&result, &reference.y);
        assert!(value > 40.0, "{name}: PSNR {value} dB is not > 40 dB");
    }
}

// ---------------------------------------------------------------------------
// PHASE3-9: unit tests for the synthesis parameters (fft_size,
// frame_period_ms, fs).

/// A valid `(f0, spectrogram, aperiodicity)` triple for `f0_length` frames and
/// the given `fft_size`, with a smooth positive envelope and the default
/// aperiodicity.
fn valid_inputs(f0_length: usize, fft_size: usize) -> (Vec<f64>, Vec<Vec<f64>>, Vec<Vec<f64>>) {
    let bins = fft_size / 2 + 1;
    let f0 = vec![200.0; f0_length];
    let spectrogram = (0..f0_length)
        .map(|i| {
            (0..bins)
                .map(|j| 1.0 + 0.5 * (0.3 * j as f64).cos() + 0.05 * i as f64)
                .collect()
        })
        .collect();
    let aperiodicity = vec![vec![0.5; bins]; f0_length];
    (f0, spectrogram, aperiodicity)
}

/// `fft_size` parameter: synthesis runs for several FFT sizes (all power-of-two
/// sizes the validation accepts), the output length is independent of
/// `fft_size` (it is `y_length`), and the output is finite and non-zero for a
/// voiced contour.
#[test]
fn synthesis_parameter_fft_size() {
    for fft_size in [128usize, 256, 1024, 2048] {
        let (f0, spectrogram, aperiodicity) = valid_inputs(21, fft_size);
        let y_length = get_y_length(21, 5.0, 16000.0);
        let y = synthesis(
            &f0,
            21,
            &spectrogram,
            &aperiodicity,
            fft_size,
            5.0,
            16000.0,
            y_length,
        )
        .unwrap_or_else(|e| panic!("fft_size={fft_size}: {e}"));
        assert_eq!(y.len(), y_length, "fft_size={fft_size}");
        let max: f64 = y.iter().map(|v| v.abs()).fold(0.0, f64::max);
        assert!(max > 0.0, "fft_size={fft_size}: output is zero");
        for &v in &y {
            assert!(v.is_finite(), "fft_size={fft_size}: non-finite sample");
        }
    }
}

/// `frame_period_ms` parameter: the output length scales linearly with the
/// frame period (`get_y_length`), and synthesis succeeds and stays finite for
/// both a 5 ms and a 10 ms grid on the same contour.
#[test]
fn synthesis_parameter_frame_period() {
    let (f0, spectrogram, aperiodicity) = valid_inputs(21, 128);
    for frame_period_ms in [5.0f64, 10.0] {
        let y_length = get_y_length(21, frame_period_ms, 16000.0);
        let y = synthesis(
            &f0,
            21,
            &spectrogram,
            &aperiodicity,
            128,
            frame_period_ms,
            16000.0,
            y_length,
        )
        .unwrap_or_else(|e| panic!("frame_period_ms={frame_period_ms}: {e}"));
        assert_eq!(y.len(), y_length);
        let max: f64 = y.iter().map(|v| v.abs()).fold(0.0, f64::max);
        assert!(
            max > 0.0,
            "frame_period_ms={frame_period_ms}: output is zero"
        );
        for &v in &y {
            assert!(
                v.is_finite(),
                "frame_period_ms={frame_period_ms}: non-finite"
            );
        }
    }
    // 10 ms spans twice the duration of 5 ms for the same frame count.
    assert_eq!(
        get_y_length(21, 10.0, 16000.0),
        2 * get_y_length(21, 5.0, 16000.0) - 1
    );
}

/// `fs` parameter: synthesis runs at both 16 kHz and 48 kHz (different pulse
/// rates and `lowest_f0` guards), the output length follows `get_y_length`,
/// and the output is finite and non-zero.
#[test]
fn synthesis_parameter_fs() {
    for fs in [16000.0f64, 48000.0] {
        let fft_size = if fs == 16000.0 { 1024 } else { 2048 };
        let (f0, spectrogram, aperiodicity) = valid_inputs(21, fft_size);
        let y_length = get_y_length(21, 5.0, fs);
        let y = synthesis(
            &f0,
            21,
            &spectrogram,
            &aperiodicity,
            fft_size,
            5.0,
            fs,
            y_length,
        )
        .unwrap_or_else(|e| panic!("fs={fs}: {e}"));
        assert_eq!(y.len(), y_length);
        let max: f64 = y.iter().map(|v| v.abs()).fold(0.0, f64::max);
        assert!(max > 0.0, "fs={fs}: output is zero");
        for &v in &y {
            assert!(v.is_finite(), "fs={fs}: non-finite sample");
        }
    }
}
